service: SwingNotesApi
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  profile: ${env:PROFILE}
  region: eu-north-1
  iam:
    role: ${env:LAMBDA_ROLE}
  deploymentMethod: direct

useDotenv: true

plugins:
  - serverless-webpack

package:
  individually: true

functions:
  GetNotes:
    handler: functions/GetNotes/index.handler
    events:
      - httpApi:
          path: /api/notes
          method: GET
  PostNotes:
    handler: functions/PostNotes/index.handler
    events:
      - httpApi:
          path: /api/notes
          method: POST
  PutNotes:
    handler: functions/PutNotes/index.handler
    events:
      - httpApi:
          path: /api/notes/{id}
          method: PUT
  DeleteNotes:
    handler: functions/DeleteNotes/index.handler
    events:
      - httpApi:
          path: /api/notes/{id}
          method: DELETE
  PostSignup:
    handler: functions/PostSignup/index.handler
    events:
      - httpApi:
          path: /api/user/signup
          method: POST
  PostLogin:
    handler: functions/PostLogin/index.handler
    events:
      - httpApi:
          path: /api/user/login
          method: POST

resources:
  Resources:
    NotesDynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Notes
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    UsersDynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Users
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
